export interface Users  {
   id: string;
   createdBy: string;
   dateCreated: string;
   lastModifiedBy: string;
   dateLastModified: string;
   userName : string;
   firstName : string;
   lastName:string; 
   email : string;
   password:  string;
   dob : string;
   nationality : string;
   country : string;
   idType : string;
   idNumber : string;
   attachment : string;
   phoneNumber : string;
   role : string;
   roleId : string;
   experience : string;
   description : string;
   Details:string;
   GovtIdDetails:string;
   ProfileUrl:string;   
   PortfolioDetails:string;
   EducationDetails:string;
   WorkingDetails:string;
   BankingDetails:string;
}