export interface Users  {
   id: string;
   createdBy: string;
   dateCreated: string;
   lastModifiedBy: string;
   dateLastModified: string;
   userName : string;
   firstName : string;
   lastName:string; 
   email : string;
   password:  string;
   dob : string;
   nationality : string;
   country : string;
   idType : string;
   idNumber : string;
   attachment : string;
   phoneNumber : string;
   role : string;
   roleId : string;
   experience : string;
   description : string;
   details:string;
   govtIdDetails:string;
   profileUrl:string;   
   portfolioDetails:string;
   educationDetails:string;
   workingDetails:string;
   bankingDetails:string;
   paymentVerify:string;
}